<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Environmental Health Alert</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f8fafc; color: #1e293b; margin: 0; padding: 0; -webkit-font-smoothing: antialiased; }
        .wrapper { width: 100%; max-width: 600px; margin: 24px auto; background: #ffffff; border-radius: 16px; border: 1px solid #e2e8f0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }
        .header { background-color: #dc2626; padding: 30px 20px; text-align: center; color: #ffffff; }
        .header h1 { margin: 0; font-size: 22px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; }
        .content { padding: 32px 24px; line-height: 1.6; }
        .greeting { font-size: 16px; font-weight: 700; color: #0f172a; margin-bottom: 12px; }
        .intro { font-size: 14px; color: #475569; margin-bottom: 24px; }
        
        /* Dashboard Matrix Callouts */
        .grid-box { background: #fff1f2; border: 1px solid #ffe4e6; border-left: 5px solid #dc2626; padding: 18px; margin-bottom: 24px; border-radius: 8px; }
        .grid-title { font-size: 12px; font-weight: 800; text-transform: uppercase; color: #991b1b; letter-spacing: 0.5px; margin-bottom: 6px; }
        .grid-val { font-size: 24px; font-weight: 900; color: #991b1b; margin-bottom: 4px; }
        
        .waste-box { background: #f8fafc; border: 1px solid #e2e8f0; border-left: 5px solid #64748b; padding: 18px; margin-bottom: 24px; border-radius: 8px; }
        .waste-title { font-size: 12px; font-weight: 800; text-transform: uppercase; color: #334155; letter-spacing: 0.5px; margin-bottom: 6px; }
        .waste-warning { font-size: 14px; font-weight: 700; color: #0f172a; }
        
        h2 { font-size: 15px; font-weight: 800; text-transform: uppercase; color: #0f172a; margin-top: 28px; margin-bottom: 12px; letter-spacing: 0.3px; border-bottom: 2px solid #f1f5f9; padding-bottom: 6px; }
        ul { margin: 0; padding-left: 20px; }
        li { margin-bottom: 10px; font-size: 14px; color: #334155; }
        .highlight { font-weight: 700; color: #0f172a; }
        
        .footer { background: #f1f5f9; padding: 20px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; font-weight: 500; }
    </style>
</head>
<body>

<div class="wrapper">
    <div class="header">
        <h1>⚠️ Critical Environmental Health Alert</h1>
    </div>

    <div class="content">
        <p class="greeting">Dear {{ $user->name }},</p>
        <p class="intro">This automated warning has been generated by your ward tracking platform. Our system has cross-referenced real-time data streaming from your neighborhood's IoT environmental nodes with recently filed municipal waste management data logs. Air indexes have fallen below healthy baseline conditions.</p>

        <!-- Section 1: Live IoT Sensor Telemetry Reading -->
        <div class="grid-box">
            <div class="grid-title">Live Sensor Reading Summary (Your Ward)</div>
            <div class="grid-val">AQI: {{ $iotReading->aqi }}</div>
            <div class="intro" style="margin: 0; font-size: 12px; color: #b91c1c; font-weight: 600;">
                Particulate Matter Breakdown: PM₂.₅: {{ $iotReading->pm2_5 }} µg/m³ | PM₁₀: {{ $iotReading->pm10 }} µg/m³
            </div>
        </div>

        <!-- Section 2: Municipal Waste Verification Check -->
        <div class="waste-box">
            <div class="waste-title">Municipal Waste Assessment Check</div>
            <div class="waste-warning">Waste Health Status: {{ $wasteRecord ? $wasteRecord->health_risk_level : 'Unreported' }}</div>
            <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569; font-style: italic;">
                "{{ $wasteRecord ? $wasteRecord->health_warning : 'No manual waste assessment logged for this period.' }}"
            </p>
            @if($wasteRecord && $wasteRecord->overflow_spots > 0)
                <div style="margin-top: 6px; font-size: 12px; font-weight: 700; color: #b91c1c;">
                    ⚠️ Warning: {{ $wasteRecord->overflow_spots }} garbage accumulation overflow spots detected in this area.
                </div>
            @endif
        </div>

        <!-- Section 3: Detailed Medical Effects -->
        <h2>⚠️ Dangerous Health Effects</h2>
        <ul>
            <li><span class="highlight">Respiratory System Strain:</span> Suspended micro-particles penetrate lung tissue deep down, causing intense coughing, throat scratching, wheezing, or tightness in the chest.</li>
            <li><span class="highlight">Waste Vector Risks:</span> Elevated landfill accumulation mixed with damp surfaces or open combustion exponentially worsens toxic air composition and attracts pests.</li>
            <li><span class="highlight">High-Risk Vulnerabilities:</span> Children, the elderly, pregnant individuals, and anyone tracking asthma or cardiac histories face immediate health risks.</li>
        </ul>

        <!-- Section 4: Mandatory Precautions -->
        <h2>🛡️ Mandatory Safety Precautions</h2>
        <ul>
            <li><span class="highlight">Seal Open Venting:</span> Keep all household windows, balcony doorways, and external entry seals locked tight to halt toxic migration indoors.</li>
            <li><span class="highlight">Halt Outdoor Activity:</span> Avoid outdoor exercises, jogging, or labor. Move any training activities fully indoors.</li>
            <li><span class="highlight">Wear High-Grade Masks:</span> If traveling outdoors is completely unavoidable, use an N95 or superior air filtration mask. Standard cloth masks do not filter out tiny PM2.5 particles.</li>
            <li><span class="highlight">Isolate Local Refuse:</span> Keep household waste containers covered tightly to stop active organic chemical degradation from creating strong odors near living areas.</li>
        </ul>

        <p style="margin-top: 32px; font-size: 13px; color: #64748b; font-style: italic; line-height: 1.5;">
            Our automated monitoring networks continue to parse real-time environmental metrics. A recovery dispatch will be pushed out when the regional smart grid reports air samples securely below a safe AQI threshold of 100. Please look out for vulnerable neighbors.
        </p>
    </div>

    <div class="footer">
        Municipal Environmental Safety Network Dispatch • This transmission is system-generated based on automated cross-referencing. Do not reply.
    </div>
</div>

</body>
</html>